import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../node_modules/@fortawesome/fontawesome-free/css/all.min.css";
import Navbar from "./_components/Navbar/Navbar";
import "./globals.css";
import MySessionProvider from "./_components/MySessionProvider/MySessionProvider";
import { CartContextProvider } from "./context/cartItemContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MySessionProvider>
          <CartContextProvider>
            <Navbar />
            <main className="pt-24">{children}</main>
          </CartContextProvider>
          <Toaster position="top-center" />
        </MySessionProvider>
      </body>
    </html>
  );
}
